import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { signIn, signOut } from "next-auth/react"

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const session = trpc.auth.getSession.useQuery();
  const posts = trpc.post.getAllPosts.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
        <nav className="container flex justify-center space-x-5">
          <a
            className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
            href={"/"}
          >
            HOME
          </a>
          <a
            className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
            href={"/posts"}
          >
            Posts
          </a>
          <a className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
            href={"/posts/new"}
          >
            Novo Post
          </a>
          <button onClick={() => signIn("twitch")}>Login</button>
          <button onClick={() => signOut()}>Log out</button>
        </nav>
        <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500">
          {
            session.data && 
          <>
            <picture className="flex flex-col items-center justify-center">
              <img
                className="rounded-full"
                src={session.data.user?.image ?? ''}
                alt={`Foto de Perfil do usuário ${session.data.user?.name}`}
                width={50}
                height={50}
                />
              <figcaption>{session.data.user?.name}</figcaption>
            </picture>
          </>
          }
        </div>
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <p className="text-2xl text-gray-700">This stack uses:</p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <TechnologyCard
            name="NextJS"
            description="The React framework for production"
            documentation="https://nextjs.org/"
          />
          <TechnologyCard
            name="TypeScript"
            description="Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale"
            documentation="https://www.typescriptlang.org/"
          />
          <TechnologyCard
            name="TailwindCSS"
            description="Rapidly build modern websites without ever leaving your HTML"
            documentation="https://tailwindcss.com/"
          />
          <TechnologyCard
            name="tRPC"
            description="End-to-end typesafe APIs made easy"
            documentation="https://trpc.io/"
          />
          <TechnologyCard
            name="Next-Auth"
            description="Authentication for Next.js"
            documentation="https://next-auth.js.org/"
          />
          <TechnologyCard
            name="Prisma"
            description="Build data-driven JavaScript & TypeScript apps in less time"
            documentation="https://www.prisma.io/docs/"
          />
        </div>
      </main>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
